-- ==========================================
-- SQL DDL Script for Form Descan Supabase Database
-- ==========================================

-- OPTION A: If you want to create them in a custom schema named "form-descan"
CREATE SCHEMA IF NOT EXISTS "form-descan";

-- 1. Users Table (in "form-descan" schema)
CREATE TABLE IF NOT EXISTS "form-descan"."users" (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    desa TEXT DEFAULT '',
    kecamatan TEXT DEFAULT '',
    kabupaten TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Surveys Table (in "form-descan" schema)
CREATE TABLE IF NOT EXISTS "form-descan"."surveys" (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES "form-descan"."users"(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),

    -- BLOK I: KETERANGAN IDENTITAS KELUARGA
    nama_kk TEXT,
    nik_kk TEXT,
    no_kk TEXT,
    jml_anggota_kk INTEGER,
    jml_anggota_pendataan INTEGER,
    provinsi TEXT,
    kabupaten_kota TEXT,
    kecamatan TEXT,
    desa_kelurahan TEXT,
    klasifikasi_desa TEXT,
    kode_pos TEXT,
    kode_sls TEXT,
    nama_sls TEXT,
    alamat TEXT,
    nama_jalan TEXT,
    no_rumah TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    alamat_sesuai_kk TEXT,

    -- BLOK II: KETERANGAN PERUMAHAN
    jml_keluarga_tinggal INTEGER,
    no_kk_lain TEXT,
    jenis_bangunan TEXT,
    nama_no_lantai TEXT,
    status_kepemilikan TEXT,
    bukti_kepemilikan TEXT,
    sewa_perkiraan TEXT,
    luas_lantai DOUBLE PRECISION,
    bahan_lantai TEXT,
    kondisi_lantai TEXT,
    bahan_dinding TEXT,
    kondisi_dinding TEXT,
    bahan_atap TEXT,
    kondisi_atap TEXT,
    fasilitas_bab TEXT,
    jenis_kloset TEXT,
    pembuangan_tinja TEXT,
    sumber_air_minum TEXT,
    sumber_penerangan TEXT,
    meteran_pln_count INTEGER,
    daya_meteran1 TEXT,
    daya_meteran2 TEXT,
    id_pelanggan1 TEXT,
    id_pelanggan2 TEXT,
    pengeluaran_listrik TEXT,
    pengeluaran_internet TEXT,
    foto_depan_url TEXT,
    foto_tamu_url TEXT,
    foto_mandi_url TEXT,

    -- BLOK III: KETERANGAN KEPEMILIKAN ASET
    gas3kg INTEGER,
    gas5kg_plus INTEGER,
    kulkas INTEGER,
    ac INTEGER,
    emas DOUBLE PRECISION,
    komputer INTEGER,
    motor INTEGER,
    motor_nilai TEXT,
    mobil INTEGER,
    mobil_nilai TEXT,
    tanah_lain INTEGER,
    tanah_lain_nilai TEXT,
    rumah_lain INTEGER,
    rumah_lain_nilai TEXT
);

-- 3. Family Members Table (in "form-descan" schema)
CREATE TABLE IF NOT EXISTS "form-descan"."family_members" (
    id TEXT PRIMARY KEY,
    survey_id TEXT REFERENCES "form-descan"."surveys"(id) ON DELETE CASCADE,
    no_urut INTEGER NOT NULL,
    nama TEXT NOT NULL,
    nik TEXT,
    no_hp TEXT,
    keberadaan TEXT,
    alamat_domisili TEXT,
    provinsi_domisili TEXT,
    kabupaten_domisili TEXT,
    negara_domisili TEXT,
    jenis_kelamin TEXT,
    tgl_lahir TEXT,
    status_kawin TEXT,
    hubungan_kk TEXT,
    partisipasi_sekolah TEXT,
    ijazah_tertinggi TEXT,
    gaji TEXT,
    tunjangan TEXT,
    uang_makan TEXT,
    honor TEXT,
    lembur TEXT,
    pendapatan_lain TEXT,
    total_pendapatan TEXT,
    pendapatan_usaha TEXT,
    pendapatan_passive TEXT,
    profesi TEXT,
    status_pekerjaan TEXT,
    disabilitas_fisik TEXT,
    disabilitas_mental TEXT,
    disabilitas_intelektual TEXT,
    disabilitas_netra TEXT,
    disabilitas_rungu TEXT,
    disabilitas_wicara TEXT,
    hipertensi TEXT,
    rematik TEXT,
    asma TEXT,
    jantung TEXT,
    diabetes TEXT,
    tbc TEXT,
    stroke TEXT,
    kanker TEXT,
    ginjal TEXT,
    hemofilia TEXT,
    hiv TEXT,
    kolesterol TEXT,
    sirosis TEXT,
    talasemia TEXT,
    leukemia TEXT,
    alzheimer TEXT,
    sakit_lainnya TEXT,
    rekening_digital TEXT
);


-- ==========================================
-- OPTION B: Standard Public Schema Tables (matches existing backend code out-of-the-box)
-- ==========================================

-- 1. Users Table (in "public" schema)
CREATE TABLE IF NOT EXISTS public."form-descan-users" (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    desa TEXT DEFAULT '',
    kecamatan TEXT DEFAULT '',
    kabupaten TEXT DEFAULT '',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- 2. Surveys Table (in "public" schema)
CREATE TABLE IF NOT EXISTS public."form-descan-surveys" (
    id TEXT PRIMARY KEY,
    user_id TEXT REFERENCES public."form-descan-users"(id) ON DELETE CASCADE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),

    -- BLOK I: KETERANGAN IDENTITAS KELUARGA
    nama_kk TEXT,
    nik_kk TEXT,
    no_kk TEXT,
    jml_anggota_kk INTEGER,
    jml_anggota_pendataan INTEGER,
    provinsi TEXT,
    kabupaten_kota TEXT,
    kecamatan TEXT,
    desa_kelurahan TEXT,
    klasifikasi_desa TEXT,
    kode_pos TEXT,
    kode_sls TEXT,
    nama_sls TEXT,
    alamat TEXT,
    nama_jalan TEXT,
    no_rumah TEXT,
    latitude DOUBLE PRECISION,
    longitude DOUBLE PRECISION,
    alamat_sesuai_kk TEXT,

    -- BLOK II: KETERANGAN PERUMAHAN
    jml_keluarga_tinggal INTEGER,
    no_kk_lain TEXT,
    jenis_bangunan TEXT,
    nama_no_lantai TEXT,
    status_kepemilikan TEXT,
    bukti_kepemilikan TEXT,
    sewa_perkiraan TEXT,
    luas_lantai DOUBLE PRECISION,
    bahan_lantai TEXT,
    kondisi_lantai TEXT,
    bahan_dinding TEXT,
    kondisi_dinding TEXT,
    bahan_atap TEXT,
    kondisi_atap TEXT,
    fasilitas_bab TEXT,
    jenis_kloset TEXT,
    pembuangan_tinja TEXT,
    sumber_air_minum TEXT,
    sumber_penerangan TEXT,
    meteran_pln_count INTEGER,
    daya_meteran1 TEXT,
    daya_meteran2 TEXT,
    id_pelanggan1 TEXT,
    id_pelanggan2 TEXT,
    pengeluaran_listrik TEXT,
    pengeluaran_internet TEXT,
    foto_depan_url TEXT,
    foto_tamu_url TEXT,
    foto_mandi_url TEXT,

    -- BLOK III: KETERANGAN KEPEMILIKAN ASET
    gas3kg INTEGER,
    gas5kg_plus INTEGER,
    kulkas INTEGER,
    ac INTEGER,
    emas DOUBLE PRECISION,
    komputer INTEGER,
    motor INTEGER,
    motor_nilai TEXT,
    mobil INTEGER,
    mobil_nilai TEXT,
    tanah_lain INTEGER,
    tanah_lain_nilai TEXT,
    rumah_lain INTEGER,
    rumah_lain_nilai TEXT
);

-- 3. Family Members Table (in "public" schema)
CREATE TABLE IF NOT EXISTS public."form-descan-family_members" (
    id TEXT PRIMARY KEY,
    survey_id TEXT REFERENCES public."form-descan-surveys"(id) ON DELETE CASCADE,
    no_urut INTEGER NOT NULL,
    nama TEXT NOT NULL,
    nik TEXT,
    no_hp TEXT,
    keberadaan TEXT,
    alamat_domisili TEXT,
    provinsi_domisili TEXT,
    kabupaten_domisili TEXT,
    negara_domisili TEXT,
    jenis_kelamin TEXT,
    tgl_lahir TEXT,
    status_kawin TEXT,
    hubungan_kk TEXT,
    partisipasi_sekolah TEXT,
    ijazah_tertinggi TEXT,
    gaji TEXT,
    tunjangan TEXT,
    uang_makan TEXT,
    honor TEXT,
    lembur TEXT,
    pendapatan_lain TEXT,
    total_pendapatan TEXT,
    pendapatan_usaha TEXT,
    pendapatan_passive TEXT,
    profesi TEXT,
    status_pekerjaan TEXT,
    disabilitas_fisik TEXT,
    disabilitas_mental TEXT,
    disabilitas_intelektual TEXT,
    disabilitas_netra TEXT,
    disabilitas_rungu TEXT,
    disabilitas_wicara TEXT,
    hipertensi TEXT,
    rematik TEXT,
    asma TEXT,
    jantung TEXT,
    diabetes TEXT,
    tbc TEXT,
    stroke TEXT,
    kanker TEXT,
    ginjal TEXT,
    hemofilia TEXT,
    hiv TEXT,
    kolesterol TEXT,
    sirosis TEXT,
    talasemia TEXT,
    leukemia TEXT,
    alzheimer TEXT,
    sakit_lainnya TEXT,
    rekening_digital TEXT
);
