import { pgTable, text, integer, doublePrecision, timestamp, uuid } from 'drizzle-orm/pg-core';

// 1. Users Table
export const users = pgTable('form-descan-users', {
  id: text('id').primaryKey(),
  email: text('email').notNull().unique(),
  password: text('password').notNull(),
  desa: text('desa').default(''),
  kecamatan: text('kecamatan').default(''),
  kabupaten: text('kabupaten').default(''),
  nama: text('nama').default(''),
  role: text('role').default('Pencacah'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});

// 2. Surveys Table
export const surveys = pgTable('form-descan-surveys', {
  id: text('id').primaryKey(),
  userId: text('user_id').references(() => users.id).notNull(),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),

  // BLOK I: KETERANGAN IDENTITAS KELUARGA
  namaKk: text('nama_kk'),
  nikKk: text('nik_kk'),
  noKk: text('no_kk'),
  jmlAnggotaKk: integer('jml_anggota_kk'),
  jmlAnggotaPendataan: integer('jml_anggota_pendataan'),
  provinsi: text('provinsi'),
  kabupatenKota: text('kabupaten_kota'),
  kecamatan: text('kecamatan'),
  desaKelurahan: text('desa_kelurahan'),
  klasifikasiDesa: text('klasifikasi_desa'), // 1=Perkotaan, 2=Perdesaan
  kodePos: text('kode_pos'),
  kodeSls: text('kode_sls'),
  namaSls: text('nama_sls'),
  alamat: text('alamat'),
  namaJalan: text('nama_jalan'),
  noRumah: text('no_rumah'),
  latitude: doublePrecision('latitude'),
  longitude: doublePrecision('longitude'),
  alamatSesuaiKk: text('alamat_sesuai_kk'), // 1=Ya, 2=Tidak

  // BLOK II: KETERANGAN PERUMAHAN
  jmlKeluargaTinggal: integer('jml_keluarga_tinggal'),
  noKkLain: text('no_kk_lain'),
  jenisBangunan: text('jenis_bangunan'),
  namaNoLantai: text('nama_no_lantai'),
  statusKepemilikan: text('status_kepemilikan'),
  buktiKepemilikan: text('bukti_kepemilikan'),
  sewaPerkiraan: text('sewa_perkiraan'),
  luasLantai: doublePrecision('luas_lantai'),
  bahanLantai: text('bahan_lantai'),
  kondisiLantai: text('kondisi_lantai'),
  bahanDinding: text('bahan_dinding'),
  kondisiDinding: text('kondisi_dinding'),
  bahanAtap: text('bahan_atap'),
  kondisiAtap: text('kondisi_atap'),
  fasilitasBab: text('fasilitas_bab'),
  jenisKloset: text('jenis_kloset'),
  pembuanganTinja: text('pembuangan_tinja'),
  sumberAirMinum: text('sumber_air_minum'),
  sumberPenerangan: text('sumber_penerangan'),
  meteranPlnCount: integer('meteran_pln_count'),
  dayaMeteran1: text('daya_meteran1'),
  dayaMeteran2: text('daya_meteran2'),
  idPelanggan1: text('id_pelanggan1'),
  idPelanggan2: text('id_pelanggan2'),
  pengeluaranListrik: text('pengeluaran_listrik'),
  pengeluaranInternet: text('pengeluaran_internet'),
  fotoDepanUrl: text('foto_depan_url'),
  fotoTamuUrl: text('foto_tamu_url'),
  fotoMandiUrl: text('foto_mandi_url'),

  // BLOK III: KETERANGAN KEPEMILIKAN ASET
  gas3kg: integer('gas3kg'),
  gas5kgPlus: integer('gas5kg_plus'),
  kulkas: integer('kulkas'),
  ac: integer('ac'),
  emas: doublePrecision('emas'),
  komputer: integer('komputer'),
  motor: integer('motor'),
  motorNilai: text('motor_nilai'),
  mobil: integer('mobil'),
  mobilNilai: text('mobil_nilai'),
  tanahLain: integer('tanah_lain'),
  tanahLainNilai: text('tanah_lain_nilai'),
  rumahLain: integer('rumah_lain'),
  rumahLainNilai: text('rumah_lain_nilai'),
});

// 3. Family Members Table
export const familyMembers = pgTable('form-descan-family_members', {
  id: text('id').primaryKey(),
  surveyId: text('survey_id').references(() => surveys.id).notNull(),
  noUrut: integer('no_urut').notNull(),
  nama: text('nama').notNull(),
  nik: text('nik'),
  noHp: text('no_hp'),
  keberadaan: text('keberadaan'),
  alamatDomisili: text('alamat_domisili'),
  provinsiDomisili: text('provinsi_domisili'),
  kabupatenDomisili: text('kabupaten_domisili'),
  negaraDomisili: text('negara_domisili'),
  jenisKelamin: text('jenis_kelamin'),
  tglLahir: text('tgl_lahir'),
  statusKawin: text('status_kawin'),
  hubunganKk: text('hubungan_kk'),
  partisipasiSekolah: text('partisipasi_sekolah'),
  ijazahTertinggi: text('ijazah_tertinggi'),
  gaji: text('gaji'),
  tunjangan: text('tunjangan'),
  uangMakan: text('uang_makan'),
  honor: text('honor'),
  lembur: text('lembur'),
  pendapatanLain: text('pendapatan_lain'),
  totalPendapatan: text('total_pendapatan'),
  pendapatanUsaha: text('pendapatan_usaha'),
  pendapatanPassive: text('pendapatan_passive'),
  profesi: text('profesi'),
  statusPekerjaan: text('status_pekerjaan'),
  disabilitasFisik: text('disabilitas_fisik'),
  disabilitasMental: text('disabilitas_mental'),
  disabilitasIntelektual: text('disabilitas_intelektual'),
  disabilitasNetra: text('disabilitas_netra'),
  disabilitasRungu: text('disabilitas_rungu'),
  disabilitasWicara: text('disabilitas_wicara'),
  hipertensi: text('hipertensi'),
  rematik: text('rematik'),
  asma: text('asma'),
  jantung: text('jantung'),
  diabetes: text('diabetes'),
  tbc: text('tbc'),
  stroke: text('stroke'),
  kanker: text('kanker'),
  ginjal: text('ginjal'),
  hemofilia: text('hemofilia'),
  hiv: text('hiv'),
  kolesterol: text('kolesterol'),
  sirosis: text('sirosis'),
  talasemia: text('talasemia'),
  leukemia: text('leukemia'),
  alzheimer: text('alzheimer'),
  sakitLainnya: text('sakit_lainnya'),
  rekeningDigital: text('rekening_digital'),
});

// 4. Wilayah Sangihe Table
export const wilayahSangihe = pgTable('form-descan-wilayah-sangihe', {
  idSubsls: text('id_subsls').primaryKey(),
  kdProv: text('kd_prov').notNull(),
  kdKab: text('kd_kab').notNull(),
  kdKec: text('kd_kec').notNull(),
  kdDesa: text('kd_desa').notNull(),
  kdSls: text('kd_sls').notNull(),
  namaProv: text('nama_prov').notNull(),
  namaKab: text('nama_kab').notNull(),
  namaKec: text('nama_kec').notNull(),
  namaDesa: text('nama_desa').notNull(),
  namaSls: text('nama_sls').notNull(),
  kdPos: text('kd_pos').default('').notNull(),
});

